name: JsonParser tesztek

on: 
  push
jobs:
  build_and_test: 
    runs-on: ubuntu-latest
    container: dobaybalazs/cadboleny_doxyandtests:latest
    steps: 
      - uses: actions/checkout@v2
      - name: Unit tesztek
        run: make Unit-tests