name: Outputtests and memcheck workflow

on:
  push
jobs:
  bulid_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        run: make build-game
      - name: Give permission to script
        run: make permission
      - name: Run test
        run: make output-tests 
      - name: Check output
        run: make io-diff-tests
      - name: cppcheck
        run: make static-code-analysis
      - name: Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact.txt
      - name: memory check
        run: make memory-leak-check
