name: Feladat2 workflow

on:
  push
jobs:
  bulid_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        run: g++ -std=c++17 *.cpp
      - name: Give permission to script
        run: chmod +x ./run_test.sh ./static_check.sh
      - name: Run test
        run: ./run_test.sh 
      - name: Check output
        run: diff output.txt good_output.txt
      - name: install cppcheck
        run: sudo apt-get install cppcheck
      - name: run cppcheck
        run: cppcheck *.cpp --enable=warning --output-file=errors.txt
      - name: check cppcheck result
        run: ./static_check.sh
      - name:  Checking for style and performance
        run: cppcheck *.cpp --enable=style --enable=performance --output-file=artifact.txt
      - name: Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact.txt