name: Feladat2 workflow

on:
  push
jobs:
  bulid-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - run: chmod +x ./run_test.sh
      - run: ./run_test.sh 
      - run: diff output.txt good_output.txt